name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract Version from package.json
        id: project_version
        run: echo "::set-output name=version::$(node -e 'console.log(require("./package.json").version)')"

      - name: test echo
        run: echo ${{ secrets.DOCKER_USERNAME }}

      - name: test echo2
        run: echo ${{ secrets }}

      - name: test echo2
        run: echo ${{ secrets.test.TESTIKO }}

      - name: Build the Docker Image
        run: |
          docker build \
            --file Dockerfile-dev \
            --tag robolaunchio/frontend-public:${{ steps.project_version.outputs.version }}-dev \
            .

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker Image to Docker Hub
        run: docker push robolaunchio/frontend-public:${{ steps.project_version.outputs.version }}-dev
